name: Deploy Backend to Hetzner VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy backend to Hetzner VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "Node: $(which node) - $(node -v)"
            echo "NPM: $(which npm) - $(npm -v)"
            echo "PM2: $(which pm2) - $(pm2 -v)"

            cd /var/www/marketplace/markeetplace-backed
            git pull origin main
          
            pm2 restart marketplace-backend --update-env
            pm2 save
            echo "Backend deployed successfully at $(date)"